AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 25

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: hash_rockets

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Style/EmptyLinesAroundModuleBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/IndentHash:
  EnforcedStyle: consistent

Style/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
  SupportedStyles:
    - aligned
    - indented

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Lambda:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: false

Performance/Casecmp:
  Enabled: false
